//! The Markdown Card format.
//!
//! A Card's stored text is one Markdown document:
//!
//! ```text
//! # <title>
//!
//! <body Markdown>
//!
//! <!-- zt:reverse-links -->
//! <generated Reverse link section>
//! ```
//!
//! The title is the leading ATX level-one heading. Everything after the
//! Reverse link marker is generated by ZT and replaced on every save; the
//! marker is an HTML comment so that rendered Markdown hides it.

use anyhow::{Result, bail};

pub(crate) const REVERSE_MARKER: &str = "<!-- zt:reverse-links -->";
pub(crate) const REVERSE_HEADING: &str = "## Reverse links";
const LEGACY_DELIM: &str = "<--->";

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct ParsedCard {
    pub(crate) title: String,
    pub(crate) body: String,
    pub(crate) reverse: String,
}

/// Parse a Topic or Regular Card, which must open with a `# Title` heading.
pub(crate) fn parse_card_text(text: &str) -> Result<ParsedCard> {
    parse(text, true)
}

/// Parse edited Literature Card text. Its title comes from BibTeX metadata,
/// so a leading `# Title` heading is optional and ignored by callers.
pub(crate) fn parse_literature_edit_text(text: &str) -> Result<ParsedCard> {
    parse(text, false)
}

fn parse(text: &str, require_title: bool) -> Result<ParsedCard> {
    let lines: Vec<&str> = text.lines().collect();
    let markers: Vec<usize> = lines
        .iter()
        .enumerate()
        .filter_map(|(idx, line)| (line.trim() == REVERSE_MARKER).then_some(idx))
        .collect();
    if markers.len() > 1 {
        bail!("card text must contain at most one {REVERSE_MARKER} line");
    }
    let body_end = markers.first().copied().unwrap_or(lines.len());
    let reverse = markers
        .first()
        .map(|marker| trim_blank_lines(&lines[marker + 1..]).join("\n"))
        .unwrap_or_default();
    let head = &lines[..body_end];
    let first = head.iter().position(|line| !line.trim().is_empty());
    let heading = first.and_then(|idx| title_from_heading(head[idx]).map(|title| (idx, title)));
    let (title, body_start) = match heading {
        Some((idx, title)) => (title, idx + 1),
        None if require_title => {
            bail!("card text must start with a `# Title` heading")
        }
        None => (String::new(), 0),
    };
    if require_title && title.is_empty() {
        bail!("card title cannot be empty");
    }
    Ok(ParsedCard {
        title,
        body: trim_blank_lines(&head[body_start..]).join("\n"),
        reverse,
    })
}

/// The title of an ATX level-one heading line, such as `# Title` or `# Title #`.
fn title_from_heading(line: &str) -> Option<String> {
    let rest = line
        .strip_prefix("# ")
        .or_else(|| (line == "#").then_some(""))?;
    let rest = rest.trim();
    let rest = rest.trim_end_matches('#');
    Some(if rest.is_empty() || rest.ends_with(' ') {
        rest.trim().to_string()
    } else {
        // A closing `#` run must be preceded by a space; otherwise it is text.
        line[2..].trim().to_string()
    })
}

fn trim_blank_lines<'a>(lines: &'a [&'a str]) -> &'a [&'a str] {
    let start = lines
        .iter()
        .position(|line| !line.trim().is_empty())
        .unwrap_or(lines.len());
    let end = lines
        .iter()
        .rposition(|line| !line.trim().is_empty())
        .map(|idx| idx + 1)
        .unwrap_or(start);
    &lines[start..end.max(start)]
}

pub(crate) fn compose_card_text(title: &str, body: &str, reverse: &str) -> String {
    let mut text = format!("# {title}\n\n");
    if !body.trim().is_empty() {
        text.push_str(body.trim_end_matches(['\n', '\r']));
        text.push_str("\n\n");
    }
    text.push_str(REVERSE_MARKER);
    text.push('\n');
    text.push_str(reverse);
    text
}

/// The generated Reverse link section for the given inbound sources.
pub(crate) fn reverse_section<'a>(sources: impl IntoIterator<Item = (&'a str, &'a str)>) -> String {
    let items = sources
        .into_iter()
        .map(|(address, title)| format!("- [[{address}]] {title}").trim_end().to_string())
        .collect::<Vec<_>>();
    if items.is_empty() {
        String::new()
    } else {
        format!("{REVERSE_HEADING}\n\n{}\n", items.join("\n"))
    }
}

/// The text a new Card opens with: its heading, a blank line, an empty body
/// line to write on, and the Reverse link marker.
pub(crate) fn card_template(title: &str) -> String {
    format!("# {title}\n\n\n{REVERSE_MARKER}\n")
}

pub(crate) fn topic_template(title: &str) -> String {
    card_template(title)
}

pub(crate) fn regular_template() -> String {
    card_template("")
}

/// Convert a Card stored in the pre-Markdown `<--->` format. Returns `None`
/// when the text is not in that format.
pub(crate) fn from_legacy_text(text: &str) -> Option<String> {
    let lines: Vec<&str> = text.lines().collect();
    let delimiters: Vec<usize> = lines
        .iter()
        .enumerate()
        .filter_map(|(idx, line)| (*line == LEGACY_DELIM).then_some(idx))
        .collect();
    let [first, second] = delimiters.as_slice() else {
        return None;
    };
    let title = lines[..*first].join(" ");
    let body = trim_blank_lines(&lines[first + 1..*second]).join("\n");
    Some(compose_card_text(title.trim(), &body, ""))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn compose_and_parse_round_trip_title_body_and_reverse() {
        let text = compose_card_text(
            "Title",
            "first\n\n- item",
            "## Reverse links\n\n- [[0/1]] A\n",
        );
        assert_eq!(
            text,
            "# Title\n\nfirst\n\n- item\n\n<!-- zt:reverse-links -->\n## Reverse links\n\n- [[0/1]] A\n"
        );
        let parsed = parse_card_text(&text).unwrap();
        assert_eq!(parsed.title, "Title");
        assert_eq!(parsed.body, "first\n\n- item");
        assert_eq!(parsed.reverse, "## Reverse links\n\n- [[0/1]] A");
    }

    #[test]
    fn empty_body_and_reverse_compose_to_a_heading_and_marker() {
        assert_eq!(
            compose_card_text("T", "", ""),
            "# T\n\n<!-- zt:reverse-links -->\n"
        );
        let parsed = parse_card_text("# T\n\n<!-- zt:reverse-links -->\n").unwrap();
        assert_eq!((parsed.title.as_str(), parsed.body.as_str()), ("T", ""));
    }

    #[test]
    fn templates_leave_an_empty_body_line_and_parse_to_canonical_text() {
        assert_eq!(regular_template(), "# \n\n\n<!-- zt:reverse-links -->\n");
        let parsed = parse_card_text(&topic_template("T")).unwrap();
        assert_eq!(
            compose_card_text(&parsed.title, &parsed.body, ""),
            compose_card_text("T", "", "")
        );
    }

    #[test]
    fn marker_is_optional_but_unique() {
        let parsed = parse_card_text("# T\nbody line\n").unwrap();
        assert_eq!(parsed.body, "body line");
        assert_eq!(parsed.reverse, "");
        let error =
            parse_card_text(&format!("# T\n{REVERSE_MARKER}\n{REVERSE_MARKER}\n")).unwrap_err();
        assert_eq!(
            error.to_string(),
            "card text must contain at most one <!-- zt:reverse-links --> line"
        );
    }

    #[test]
    fn regular_cards_require_a_nonempty_level_one_heading() {
        for (text, expected) in [
            (
                "no heading\n",
                "card text must start with a `# Title` heading",
            ),
            (
                "## Second level\n",
                "card text must start with a `# Title` heading",
            ),
            ("#Title\n", "card text must start with a `# Title` heading"),
            ("# \n\nbody\n", "card title cannot be empty"),
            ("", "card text must start with a `# Title` heading"),
        ] {
            assert_eq!(parse_card_text(text).unwrap_err().to_string(), expected);
        }
        assert_eq!(parse_card_text("\n\n# Late  \nx").unwrap().title, "Late");
        assert_eq!(parse_card_text("# Closed #\n").unwrap().title, "Closed");
        assert_eq!(parse_card_text("# C#\n").unwrap().title, "C#");
    }

    #[test]
    fn literature_edit_text_may_omit_the_heading() {
        let parsed = parse_literature_edit_text("just notes\n").unwrap();
        assert_eq!(
            (parsed.title.as_str(), parsed.body.as_str()),
            ("", "just notes")
        );
        let parsed = parse_literature_edit_text("# Anything\nnotes").unwrap();
        assert_eq!(parsed.body, "notes");
    }

    #[test]
    fn reverse_sections_are_markdown_lists_under_a_heading() {
        assert_eq!(reverse_section([]), "");
        assert_eq!(
            reverse_section([("0/0", "Earlier"), ("0/2", "")]),
            "## Reverse links\n\n- [[0/0]] Earlier\n- [[0/2]]\n"
        );
    }

    #[test]
    fn legacy_text_converts_title_and_body_and_drops_the_reverse_section() {
        assert_eq!(
            from_legacy_text(
                "Title\n<--->\nbody\n<--->\nThis note has been referred by note [[0/1]] X"
            )
            .as_deref(),
            Some("# Title\n\nbody\n\n<!-- zt:reverse-links -->\n")
        );
        assert_eq!(from_legacy_text("# Title\n\nbody\n"), None);
    }
}
